[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
counter = "8tJT3LSSpMXg1urHU5LpJh868eg7h5W4nLCGVessUdBz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/babar/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
